
amenities_general <- c("d_tv",
                       "d_ac",
                       "d_backyard",
                       "d_baking_sheet",
                       "d_bathtub",
                       "d_bbq",
                       "d_board_games",
                       "d_brekkie",
                       "d_coffee",
                       "d_ceiling_fan",
                       "d_clothing_storage",
                       "d_dedicated_workspace",
                       "d_dishwasher",
                       "d_dryer",
                       "d_drying_rack",
                       "d_eco",
                       "d_wifi",
                       "d_fire_guard",
                       "d_first_aid",
                       "d_fitness",
                       "d_heating",
                       "d_high_chair",
                       "d_organic",
                       "d_hot_tub",
                       "d_spa",
                       "d_fireplace",
                       "d_iron",
                       "d_bluetooth",
                       "d_nespresso",
                       "d_kitchen_aid",
                       "d_rice_maker",
                       "d_mosquito_net",
                       "d_laundromat",
                       "d_security_camera",
                       "d_free_parking",
                       "d_long_term",
                       "d_pool",
                       "d_pets_allowed",
                       "d_beachfront",
                       "d_lake_access",
                       "d_kayak",
                       "d_piano",
                       "d_pingpong")


home_appliance_brands <- c("d_danby",
                           "d_divers",
                           "d_electrolux",
                           "d_fisher_and_paykel",
                           "d_frigidaire",
                           "d_galanz",
                           "d_induction ",
                           "d_inglis",
                           "d_kenmore",
                           "d_lg",
                           "d_miele",
                           "d_samsung")

beauty_care_brands <- c("d_aroma_zone",
                        "d_attitude",
                        "d_aveda",
                        "d_bella_pella",
                        "d_costco",
                        "d_dove",
                        "d_dumarchand",
                        "d_garnier",
                        "d_head_and_shoulders",
                        "d_ivory",
                        "d_kiehls",
                        "d_kirkland",
                        "d_loreal",
                        "d_lemieux",
                        "d_melaleuca",
                        "d_nivea",
                        "d_olay",
                        "d_ordinaire",
                        "d_organix",
                        "d_pantene",
                        "d_plusieurs")

digital_entertainment <- c("d_game_console",
                           "d_nintendo",
                           "d_ps",
                           "d_alexa",
                           "d_amazon_prime",
                           "d_apple",
                           "d_bang_and_olufsen",
                           "d_beats",
                           "d_bosch",
                           "d_boombox",
                           "d_bose",
                           "d_chromecast",
                           "d_google",
                           "d_jbl",
                           "d_jvc",
                           "d_netlix",
                           "d_pioneer")

baby_children_friendly <- c("d_baby_bath",
                            "d_baby_monitor",
                            "d_baby_safety_gates",
                            "d_babysitter_rec",
                            "d_crib",
                            "d_children")

outdoor_facilities <- c("d_outdoor_dining_area",
                        "d_outdoor_furniture",
                        "d_outdoor_pool",
                        "d_outdoor_shower")

amenities <- c(amenities_general, home_appliance_brands, beauty_care_brands, digital_entertainment, baby_children_friendly, outdoor_facilities)

host_verifications <- c("d_hv_facebook",
                        "d_hv_google",
                        "d_hv_government_id",
                        "d_hv_jumio",
                        "d_hv_manual",
                        "d_hv_kba",
                        "d_hv_phone",
                        "d_hv_reviews",
                        "d_hv_selfie",
                        "d_hv_sent_id",
                        "d_hv_sesame",
                        "d_hv_email")
